- hosts:
  - zabbix_agent2

  tasks:

    - name: Install Zabbix deb from internet
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bdebian11_all.deb
      tags: zabbix_agent

    - name: install Zabbix agent2
      ansible.builtin.apt: 
        name: zabbix-agent2
        state: present
        update_cache: yes
      tags: zabbix_agent

    - name: Modify zabbix_agent2.conf
      ansible.builtin.lineinfile: dest=/etc/zabbix/zabbix_agent2.conf regexp="{{ item.var }}=" line="{{ item.var }}={{ item.value }}"
      with_items:
        - { var: "ServerActive", value: "{{ zabbix_server }}"}
        - { var: "Server", value: "{{ zabbix_server }}"}
        - { var: "Hostname", value: "{{ansible_hostname}}"}
      notify:
      - Restart zabbix agent
      tags: zabbix_agent

    - name: Adding user zabbix to group docker
      ansible.builtin.user:
        name: zabbix
        groups: docker
        append: yes
      ignore_errors: true
      notify:
      - Restart zabbix agent
      tags: zabbix_agent

  handlers:

    - name: Restart zabbix agent 
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted