- hosts:
  - zabbix_agent2

  tasks:

    - name: Download Zabbix Debian release deb file
      ansible.builtin.get_url:
        url="https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bdebian11_all.deb"
        dest="/tmp/zabbix-release.deb"
      tags: zabbix_agent      

    - name: Install Zabbix Debian release deb file
      ansible.builtin.apt: deb="/tmp/zabbix-release.deb"
      tags: zabbix_agent

    - name: Apt-get update
      ansible.builtin.apt: update_cache=yes
      tags: zabbix_agent

    - name: install Zabbix agent2
      package: 
        name: zabbix-agent2
        state: present
      tags: zabbix_agent

    - name: Modify zabbix_agent2.conf
      ansible.builtin.lineinfile: dest=/etc/zabbix/zabbix_agent2.conf regexp="{{ item.var }}=" line="{{ item.var }}={{ item.value }}"
      with_items:
        - { var: "ServerActive", value: "{{ zabbix_server }}"}
        - { var: "Server", value: "{{ zabbix_server }}"}
        - { var: "Hostname", value: "{{ansible_hostname}}"}
      tags: zabbix_agent

    - name: Adding user zabbix to group docker
      ansible.builtin.user:
        name: zabbix
        groups: docker
        append: yes
      ignore_errors: true
      tags: zabbix_agent 

    - name: Restart zabbix-agent2
      service: name=zabbix-agent2 state=restarted
      ignore_errors: yes
      tags: zabbix_agent